### ISSUE TITLE
minified javascripts

### ISSUE THREAD

**Issue by onlyjob** [osuosl/ganeti_webmgr#58]
There are some minified javascripts committed to source tree in [ganeti_webmgr/static/js](../tree/master/ganeti_webmgr/static/js), notably [jquery.tablesorter.min.js](https://raw.githubusercontent.com/osuosl/ganeti_webmgr/master/ganeti_webmgr/static/js/jquery.tablesorter.min.js) and others.

Minified javascripts are effectively the same as pre-compiled binaries --
un-readable, non-modifiable and non-distributable in
[Debian](http://debian.org). The case of `jquery.tablesorter.min.js` is particularly bad because minified version have no license and no copyright attribution.

It is the best (practice) to have no minified files in source tree at all.
Please replace all minified javascripts with their original uncompressed versions.

**Comment by tschuy** [comment]
Thanks for the issue. I'll most likely be able to get this this coming week.

**Comment by tschuy** [comment]
This will be fixed by #66 as soon as it gets merged.

**Comment by tschuy** [comment]
#66 has been merged :)

**Comment by onlyjob** [comment]
Thanks but I think resolution is incorrect... Comprehensiveness of tarball is lost and now it is no longer possible to build in clean offline environment because internet connection is required?? Besides `bower` is not available in [Debian](http://debian.org) hence lack of dependencies in source tree cause problems to downstream package maintainers... :(

**Comment by tschuy** [comment]
I'll look into using bower to manage dependencies but keeping them in the repo as well. That should satisfy that (a) the tarball distributes all source, (b) everything is properly licensed, and (c) dependencies can be easily updated. @onlyjob would this be a reasonable solution?

**Comment by onlyjob** [comment]
Yes, that would be great. Thank you.

**Comment by tschuy** [comment]
The bower dependencies are now included in the repo under ``ganeti_webmgr/bower_components/bower_components`` on develop. Thanks for the help!
