### ISSUE TITLE
when I try to access any URL after logging in I get a Terrible Event

### ISSUE THREAD

**Issue by jldugger** [osuosl/ganeti_webmgr#72]
[Mon Sep 21 16:22:08 2015] [error] ERROR:django.request:Internal Server Error: /
[Mon Sep 21 16:22:08 2015] [error] Traceback (most recent call last):
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/django/core/handlers/base.py", line 109, in get_response
[Mon Sep 21 16:22:08 2015] [error]     response = callback(request, *callback_args, **callback_kwargs)
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
[Mon Sep 21 16:22:08 2015] [error]     return view_func(request, *args, **kwargs)
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/ganeti_webmgr/ganeti_web/views/general.py", line 213, in overview
[Mon Sep 21 16:22:08 2015] [error]     orphaned, import_ready, missing = get_vm_counts(clusters)
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/ganeti_webmgr/ganeti_web/views/general.py", line 180, in get_vm_counts
[Mon Sep 21 16:22:08 2015] [error]     for cluster in clusters:
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/django/db/models/query.py", line 118, in _result_iter
[Mon Sep 21 16:22:08 2015] [error]     self._fill_cache()
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/django/db/models/query.py", line 892, in _fill_cache
[Mon Sep 21 16:22:08 2015] [error]     self._result_cache.append(self._iter.next())
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/django/db/models/query.py", line 301, in iterator
[Mon Sep 21 16:22:08 2015] [error]     obj = model(*row[index_start:aggregate_start])
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/ganeti_webmgr/clusters/models.py", line 61, in __init__
[Mon Sep 21 16:22:08 2015] [error]     self.load_info()
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/ganeti_webmgr/clusters/models.py", line 104, in load_info
[Mon Sep 21 16:22:08 2015] [error]     self.refresh()
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/ganeti_webmgr/clusters/models.py", line 136, in refresh
[Mon Sep 21 16:22:08 2015] [error]     info_ = self._refresh()
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/ganeti_webmgr/clusters/models.py", line 633, in _refresh
[Mon Sep 21 16:22:08 2015] [error]     return self.rapi.GetInfo()
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/ganeti_webmgr/utils/client.py", line 308, in GetInfo
[Mon Sep 21 16:22:08 2015] [error]     None, None)
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/ganeti_webmgr/utils/client.py", line 245, in _SendRequest
[Mon Sep 21 16:22:08 2015] [error]     r = requests.request(method, url, **kwargs)
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/requests/api.py", line 50, in request
[Mon Sep 21 16:22:08 2015] [error]     response = session.request(method=method, url=url, **kwargs)
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/requests/sessions.py", line 465, in request
[Mon Sep 21 16:22:08 2015] [error]     resp = self.send(prep, **send_kwargs)
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/requests/sessions.py", line 573, in send
[Mon Sep 21 16:22:08 2015] [error]     r = adapter.send(request, **kwargs)
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/requests/adapters.py", line 370, in send
[Mon Sep 21 16:22:08 2015] [error]     timeout=timeout
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
[Mon Sep 21 16:22:08 2015] [error]     body=body, headers=headers)
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
[Mon Sep 21 16:22:08 2015] [error]     self._validate_conn(conn)
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
[Mon Sep 21 16:22:08 2015] [error]     conn.connect()
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/requests/packages/urllib3/connection.py", line 204, in connect
[Mon Sep 21 16:22:08 2015] [error]     conn = self._new_conn()
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
[Mon Sep 21 16:22:08 2015] [error]     (self.host, self.port), self.timeout, **extra_kw)
[Mon Sep 21 16:22:08 2015] [error]   File "/opt/ganeti_webmgr/lib/python2.6/site-packages/requests/packages/urllib3/util/connection.py", line 75, in create_connection
[Mon Sep 21 16:22:08 2015] [error]     sock.settimeout(timeout)
[Mon Sep 21 16:22:08 2015] [error]   File "<string>", line 1, in settimeout
[Mon Sep 21 16:22:08 2015] [error] TypeError: a float is required

**Comment by tschuy** [comment]
Fixed by https://github.com/osuosl/chef-repo/pull/186
