### ISSUE TITLE
missing slash in menu_base.html for jquery-ui/jquery-ui.js path

### ISSUE THREAD

**Issue by abezella** [osuosl/ganeti_webmgr#84]
having installed the 0.11.2-rc1 release onto an ubuntu 14.04 host (w/mysql), i was getting an error when trying to change the owner of a vm or import a vm while attaching an owner.

on the "Change Owner" page (which apparently has the mistaken page title of "Rename Virtual Machine"), when i entered a user in the text field and clicked "Save" it returned:
> This field is required.

similarly, on the "Orphaned Virtual Machines" page when i entered a user's name and hit "Update Selected" it threw back:
> owner
>   This field is required.

in neither case was the change made, and there was no autocomplete / dropdown for the field.

eventually i found the following in the apache `access.log`:
> 208.70.27.190 - - [29/Oct/2015:21:49:00 +0000] "GET /staticjquery-ui/jquery-ui.js HTTP/1.1" 404 2894 "https://gwm.us.archive.org/users" "Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0 Iceweasel/41.0.2"

and a minor correction to `ganeti_webmgr/templates/menu_base.html` appears to resolve the issue (pull request pending; looks like it was addressed in master).

**Comment by tschuy** [comment]
Fixed by #85
